services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example 
      MONGO_INITDB_DATABASE: myappdb 
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app 

  app:
    image: mnagy156/tresmerge-docker
    env_file:
      - ./.env
    depends_on:
      - redis 

volumes:
  mongo-db:
