version: "3.8"

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example 
      MONGO_INITDB_DATABASE: myappdb 
    volumes:
      - mongo-db:/data/db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  app:
    image: mnagy156/tresmerge-docker
    env_file:
      - ./.env
    depends_on:
      - redis
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s

volumes:
  mongo-db:
