services:
  app:  
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - PORT=4000
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379  
      - DB_UNAME=nagy
      - DB_PASSWD=20012409
      - PGHOST=localhost
      - PGUSER=myuser
      - PGPASSWORD=mypassword
      - PGDATABASE=mydatabase
      - PGPORT=5432 
    command: npm run start-dev
