services:
  app:
    build:
      context: .
      args: 
        - NODE_ENV=production
    container_name: my-express-app
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: npm start
