services:
  app:  
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - PORT=4000
      - NODE_ENV=development 
    command: npm run start-dev
