version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example 
      MONGO_INITDB_DATABASE: myappdb 
    volumes:
      - mongo-db:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app 

  app:
    container_name: my-express-app
    image: your_express_app_image
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - redis 

volumes:
  mongo-db:
