services:
  app:
    container_name: my-express-app
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src:ro
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - NODE_ENV=production
