services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example 
    volumes:
      - mongo-db:/data/db

  app:
    container_name: my-express-app
    ports:
      - "4000:4000"  
    env_file:
      - ./.env

volumes:
  mongo-db:
      